// Code generated by gen.go; DO NOT EDIT.

package banprice

// extraFinishes are the finishes MoreFinishes carries, in field order.
var extraFinishes = []string{
	"rainbowfoil",
	"coldfoil",
	"holofoil",
	"reverseholofoil",
	"1stedition",
	"unlimited",
	"limited",
	"1steditionholofoil",
	"unlimitedholofoil",
	"1steditionnormal",
	"1steditionrainbowfoil",
	"1steditioncoldfoil",
	"unlimitededitionnormal",
	"unlimitededitionrainbowfoil",
}

// MoreFinishes holds the prices and quantities of the finishes past
// nonfoil, foil and etched, which only the datastore games sell. Price
// embeds it by pointer, so its fields sit beside regular and foil on the
// wire and cost nothing for a card sold in none of them.
type MoreFinishes struct {
	RainbowFoil                    float64 `json:"rainbowfoil,omitempty"`
	ColdFoil                       float64 `json:"coldfoil,omitempty"`
	Holofoil                       float64 `json:"holofoil,omitempty"`
	ReverseHolofoil                float64 `json:"reverseholofoil,omitempty"`
	FirstEdition                   float64 `json:"1stedition,omitempty"`
	Unlimited                      float64 `json:"unlimited,omitempty"`
	Limited                        float64 `json:"limited,omitempty"`
	FirstEditionHolofoil           float64 `json:"1steditionholofoil,omitempty"`
	UnlimitedHolofoil              float64 `json:"unlimitedholofoil,omitempty"`
	FirstEditionNormal             float64 `json:"1steditionnormal,omitempty"`
	FirstEditionRainbowFoil        float64 `json:"1steditionrainbowfoil,omitempty"`
	FirstEditionColdFoil           float64 `json:"1steditioncoldfoil,omitempty"`
	UnlimitedEditionNormal         float64 `json:"unlimitededitionnormal,omitempty"`
	UnlimitedEditionRainbowFoil    float64 `json:"unlimitededitionrainbowfoil,omitempty"`
	QtyRainbowFoil                 int     `json:"qty_rainbowfoil,omitempty"`
	QtyColdFoil                    int     `json:"qty_coldfoil,omitempty"`
	QtyHolofoil                    int     `json:"qty_holofoil,omitempty"`
	QtyReverseHolofoil             int     `json:"qty_reverseholofoil,omitempty"`
	QtyFirstEdition                int     `json:"qty_1stedition,omitempty"`
	QtyUnlimited                   int     `json:"qty_unlimited,omitempty"`
	QtyLimited                     int     `json:"qty_limited,omitempty"`
	QtyFirstEditionHolofoil        int     `json:"qty_1steditionholofoil,omitempty"`
	QtyUnlimitedHolofoil           int     `json:"qty_unlimitedholofoil,omitempty"`
	QtyFirstEditionNormal          int     `json:"qty_1steditionnormal,omitempty"`
	QtyFirstEditionRainbowFoil     int     `json:"qty_1steditionrainbowfoil,omitempty"`
	QtyFirstEditionColdFoil        int     `json:"qty_1steditioncoldfoil,omitempty"`
	QtyUnlimitedEditionNormal      int     `json:"qty_unlimitededitionnormal,omitempty"`
	QtyUnlimitedEditionRainbowFoil int     `json:"qty_unlimitededitionrainbowfoil,omitempty"`
}

func (m *MoreFinishes) price(finish string) *float64 {
	switch finish {
	case "rainbowfoil":
		return &m.RainbowFoil
	case "coldfoil":
		return &m.ColdFoil
	case "holofoil":
		return &m.Holofoil
	case "reverseholofoil":
		return &m.ReverseHolofoil
	case "1stedition":
		return &m.FirstEdition
	case "unlimited":
		return &m.Unlimited
	case "limited":
		return &m.Limited
	case "1steditionholofoil":
		return &m.FirstEditionHolofoil
	case "unlimitedholofoil":
		return &m.UnlimitedHolofoil
	case "1steditionnormal":
		return &m.FirstEditionNormal
	case "1steditionrainbowfoil":
		return &m.FirstEditionRainbowFoil
	case "1steditioncoldfoil":
		return &m.FirstEditionColdFoil
	case "unlimitededitionnormal":
		return &m.UnlimitedEditionNormal
	case "unlimitededitionrainbowfoil":
		return &m.UnlimitedEditionRainbowFoil
	}
	return nil
}

func (m *MoreFinishes) qty(finish string) *int {
	switch finish {
	case "rainbowfoil":
		return &m.QtyRainbowFoil
	case "coldfoil":
		return &m.QtyColdFoil
	case "holofoil":
		return &m.QtyHolofoil
	case "reverseholofoil":
		return &m.QtyReverseHolofoil
	case "1stedition":
		return &m.QtyFirstEdition
	case "unlimited":
		return &m.QtyUnlimited
	case "limited":
		return &m.QtyLimited
	case "1steditionholofoil":
		return &m.QtyFirstEditionHolofoil
	case "unlimitedholofoil":
		return &m.QtyUnlimitedHolofoil
	case "1steditionnormal":
		return &m.QtyFirstEditionNormal
	case "1steditionrainbowfoil":
		return &m.QtyFirstEditionRainbowFoil
	case "1steditioncoldfoil":
		return &m.QtyFirstEditionColdFoil
	case "unlimitededitionnormal":
		return &m.QtyUnlimitedEditionNormal
	case "unlimitededitionrainbowfoil":
		return &m.QtyUnlimitedEditionRainbowFoil
	}
	return nil
}

// MoreConditions holds the per-grade prices of the finishes MoreFinishes
// carries, embedded by pointer for the same reason.
type MoreConditions struct {
	NMRainbowFoil                 float64 `json:"NM_rainbowfoil,omitempty"`
	NMColdFoil                    float64 `json:"NM_coldfoil,omitempty"`
	NMHolofoil                    float64 `json:"NM_holofoil,omitempty"`
	NMReverseHolofoil             float64 `json:"NM_reverseholofoil,omitempty"`
	NMFirstEdition                float64 `json:"NM_1stedition,omitempty"`
	NMUnlimited                   float64 `json:"NM_unlimited,omitempty"`
	NMLimited                     float64 `json:"NM_limited,omitempty"`
	NMFirstEditionHolofoil        float64 `json:"NM_1steditionholofoil,omitempty"`
	NMUnlimitedHolofoil           float64 `json:"NM_unlimitedholofoil,omitempty"`
	NMFirstEditionNormal          float64 `json:"NM_1steditionnormal,omitempty"`
	NMFirstEditionRainbowFoil     float64 `json:"NM_1steditionrainbowfoil,omitempty"`
	NMFirstEditionColdFoil        float64 `json:"NM_1steditioncoldfoil,omitempty"`
	NMUnlimitedEditionNormal      float64 `json:"NM_unlimitededitionnormal,omitempty"`
	NMUnlimitedEditionRainbowFoil float64 `json:"NM_unlimitededitionrainbowfoil,omitempty"`
	SPRainbowFoil                 float64 `json:"SP_rainbowfoil,omitempty"`
	SPColdFoil                    float64 `json:"SP_coldfoil,omitempty"`
	SPHolofoil                    float64 `json:"SP_holofoil,omitempty"`
	SPReverseHolofoil             float64 `json:"SP_reverseholofoil,omitempty"`
	SPFirstEdition                float64 `json:"SP_1stedition,omitempty"`
	SPUnlimited                   float64 `json:"SP_unlimited,omitempty"`
	SPLimited                     float64 `json:"SP_limited,omitempty"`
	SPFirstEditionHolofoil        float64 `json:"SP_1steditionholofoil,omitempty"`
	SPUnlimitedHolofoil           float64 `json:"SP_unlimitedholofoil,omitempty"`
	SPFirstEditionNormal          float64 `json:"SP_1steditionnormal,omitempty"`
	SPFirstEditionRainbowFoil     float64 `json:"SP_1steditionrainbowfoil,omitempty"`
	SPFirstEditionColdFoil        float64 `json:"SP_1steditioncoldfoil,omitempty"`
	SPUnlimitedEditionNormal      float64 `json:"SP_unlimitededitionnormal,omitempty"`
	SPUnlimitedEditionRainbowFoil float64 `json:"SP_unlimitededitionrainbowfoil,omitempty"`
	MPRainbowFoil                 float64 `json:"MP_rainbowfoil,omitempty"`
	MPColdFoil                    float64 `json:"MP_coldfoil,omitempty"`
	MPHolofoil                    float64 `json:"MP_holofoil,omitempty"`
	MPReverseHolofoil             float64 `json:"MP_reverseholofoil,omitempty"`
	MPFirstEdition                float64 `json:"MP_1stedition,omitempty"`
	MPUnlimited                   float64 `json:"MP_unlimited,omitempty"`
	MPLimited                     float64 `json:"MP_limited,omitempty"`
	MPFirstEditionHolofoil        float64 `json:"MP_1steditionholofoil,omitempty"`
	MPUnlimitedHolofoil           float64 `json:"MP_unlimitedholofoil,omitempty"`
	MPFirstEditionNormal          float64 `json:"MP_1steditionnormal,omitempty"`
	MPFirstEditionRainbowFoil     float64 `json:"MP_1steditionrainbowfoil,omitempty"`
	MPFirstEditionColdFoil        float64 `json:"MP_1steditioncoldfoil,omitempty"`
	MPUnlimitedEditionNormal      float64 `json:"MP_unlimitededitionnormal,omitempty"`
	MPUnlimitedEditionRainbowFoil float64 `json:"MP_unlimitededitionrainbowfoil,omitempty"`
	HPRainbowFoil                 float64 `json:"HP_rainbowfoil,omitempty"`
	HPColdFoil                    float64 `json:"HP_coldfoil,omitempty"`
	HPHolofoil                    float64 `json:"HP_holofoil,omitempty"`
	HPReverseHolofoil             float64 `json:"HP_reverseholofoil,omitempty"`
	HPFirstEdition                float64 `json:"HP_1stedition,omitempty"`
	HPUnlimited                   float64 `json:"HP_unlimited,omitempty"`
	HPLimited                     float64 `json:"HP_limited,omitempty"`
	HPFirstEditionHolofoil        float64 `json:"HP_1steditionholofoil,omitempty"`
	HPUnlimitedHolofoil           float64 `json:"HP_unlimitedholofoil,omitempty"`
	HPFirstEditionNormal          float64 `json:"HP_1steditionnormal,omitempty"`
	HPFirstEditionRainbowFoil     float64 `json:"HP_1steditionrainbowfoil,omitempty"`
	HPFirstEditionColdFoil        float64 `json:"HP_1steditioncoldfoil,omitempty"`
	HPUnlimitedEditionNormal      float64 `json:"HP_unlimitededitionnormal,omitempty"`
	HPUnlimitedEditionRainbowFoil float64 `json:"HP_unlimitededitionrainbowfoil,omitempty"`
	PORainbowFoil                 float64 `json:"PO_rainbowfoil,omitempty"`
	POColdFoil                    float64 `json:"PO_coldfoil,omitempty"`
	POHolofoil                    float64 `json:"PO_holofoil,omitempty"`
	POReverseHolofoil             float64 `json:"PO_reverseholofoil,omitempty"`
	POFirstEdition                float64 `json:"PO_1stedition,omitempty"`
	POUnlimited                   float64 `json:"PO_unlimited,omitempty"`
	POLimited                     float64 `json:"PO_limited,omitempty"`
	POFirstEditionHolofoil        float64 `json:"PO_1steditionholofoil,omitempty"`
	POUnlimitedHolofoil           float64 `json:"PO_unlimitedholofoil,omitempty"`
	POFirstEditionNormal          float64 `json:"PO_1steditionnormal,omitempty"`
	POFirstEditionRainbowFoil     float64 `json:"PO_1steditionrainbowfoil,omitempty"`
	POFirstEditionColdFoil        float64 `json:"PO_1steditioncoldfoil,omitempty"`
	POUnlimitedEditionNormal      float64 `json:"PO_unlimitededitionnormal,omitempty"`
	POUnlimitedEditionRainbowFoil float64 `json:"PO_unlimitededitionrainbowfoil,omitempty"`
}

func (m *MoreConditions) ref(tag string) *float64 {
	switch tag {
	case "NM_rainbowfoil":
		return &m.NMRainbowFoil
	case "NM_coldfoil":
		return &m.NMColdFoil
	case "NM_holofoil":
		return &m.NMHolofoil
	case "NM_reverseholofoil":
		return &m.NMReverseHolofoil
	case "NM_1stedition":
		return &m.NMFirstEdition
	case "NM_unlimited":
		return &m.NMUnlimited
	case "NM_limited":
		return &m.NMLimited
	case "NM_1steditionholofoil":
		return &m.NMFirstEditionHolofoil
	case "NM_unlimitedholofoil":
		return &m.NMUnlimitedHolofoil
	case "NM_1steditionnormal":
		return &m.NMFirstEditionNormal
	case "NM_1steditionrainbowfoil":
		return &m.NMFirstEditionRainbowFoil
	case "NM_1steditioncoldfoil":
		return &m.NMFirstEditionColdFoil
	case "NM_unlimitededitionnormal":
		return &m.NMUnlimitedEditionNormal
	case "NM_unlimitededitionrainbowfoil":
		return &m.NMUnlimitedEditionRainbowFoil
	case "SP_rainbowfoil":
		return &m.SPRainbowFoil
	case "SP_coldfoil":
		return &m.SPColdFoil
	case "SP_holofoil":
		return &m.SPHolofoil
	case "SP_reverseholofoil":
		return &m.SPReverseHolofoil
	case "SP_1stedition":
		return &m.SPFirstEdition
	case "SP_unlimited":
		return &m.SPUnlimited
	case "SP_limited":
		return &m.SPLimited
	case "SP_1steditionholofoil":
		return &m.SPFirstEditionHolofoil
	case "SP_unlimitedholofoil":
		return &m.SPUnlimitedHolofoil
	case "SP_1steditionnormal":
		return &m.SPFirstEditionNormal
	case "SP_1steditionrainbowfoil":
		return &m.SPFirstEditionRainbowFoil
	case "SP_1steditioncoldfoil":
		return &m.SPFirstEditionColdFoil
	case "SP_unlimitededitionnormal":
		return &m.SPUnlimitedEditionNormal
	case "SP_unlimitededitionrainbowfoil":
		return &m.SPUnlimitedEditionRainbowFoil
	case "MP_rainbowfoil":
		return &m.MPRainbowFoil
	case "MP_coldfoil":
		return &m.MPColdFoil
	case "MP_holofoil":
		return &m.MPHolofoil
	case "MP_reverseholofoil":
		return &m.MPReverseHolofoil
	case "MP_1stedition":
		return &m.MPFirstEdition
	case "MP_unlimited":
		return &m.MPUnlimited
	case "MP_limited":
		return &m.MPLimited
	case "MP_1steditionholofoil":
		return &m.MPFirstEditionHolofoil
	case "MP_unlimitedholofoil":
		return &m.MPUnlimitedHolofoil
	case "MP_1steditionnormal":
		return &m.MPFirstEditionNormal
	case "MP_1steditionrainbowfoil":
		return &m.MPFirstEditionRainbowFoil
	case "MP_1steditioncoldfoil":
		return &m.MPFirstEditionColdFoil
	case "MP_unlimitededitionnormal":
		return &m.MPUnlimitedEditionNormal
	case "MP_unlimitededitionrainbowfoil":
		return &m.MPUnlimitedEditionRainbowFoil
	case "HP_rainbowfoil":
		return &m.HPRainbowFoil
	case "HP_coldfoil":
		return &m.HPColdFoil
	case "HP_holofoil":
		return &m.HPHolofoil
	case "HP_reverseholofoil":
		return &m.HPReverseHolofoil
	case "HP_1stedition":
		return &m.HPFirstEdition
	case "HP_unlimited":
		return &m.HPUnlimited
	case "HP_limited":
		return &m.HPLimited
	case "HP_1steditionholofoil":
		return &m.HPFirstEditionHolofoil
	case "HP_unlimitedholofoil":
		return &m.HPUnlimitedHolofoil
	case "HP_1steditionnormal":
		return &m.HPFirstEditionNormal
	case "HP_1steditionrainbowfoil":
		return &m.HPFirstEditionRainbowFoil
	case "HP_1steditioncoldfoil":
		return &m.HPFirstEditionColdFoil
	case "HP_unlimitededitionnormal":
		return &m.HPUnlimitedEditionNormal
	case "HP_unlimitededitionrainbowfoil":
		return &m.HPUnlimitedEditionRainbowFoil
	case "PO_rainbowfoil":
		return &m.PORainbowFoil
	case "PO_coldfoil":
		return &m.POColdFoil
	case "PO_holofoil":
		return &m.POHolofoil
	case "PO_reverseholofoil":
		return &m.POReverseHolofoil
	case "PO_1stedition":
		return &m.POFirstEdition
	case "PO_unlimited":
		return &m.POUnlimited
	case "PO_limited":
		return &m.POLimited
	case "PO_1steditionholofoil":
		return &m.POFirstEditionHolofoil
	case "PO_unlimitedholofoil":
		return &m.POUnlimitedHolofoil
	case "PO_1steditionnormal":
		return &m.POFirstEditionNormal
	case "PO_1steditionrainbowfoil":
		return &m.POFirstEditionRainbowFoil
	case "PO_1steditioncoldfoil":
		return &m.POFirstEditionColdFoil
	case "PO_unlimitededitionnormal":
		return &m.POUnlimitedEditionNormal
	case "PO_unlimitededitionrainbowfoil":
		return &m.POUnlimitedEditionRainbowFoil
	}
	return nil
}

// MoreQuantities holds the per-grade quantities of the finishes MoreFinishes
// carries, embedded by pointer for the same reason.
type MoreQuantities struct {
	NMRainbowFoil                 int `json:"NM_rainbowfoil,omitempty"`
	NMColdFoil                    int `json:"NM_coldfoil,omitempty"`
	NMHolofoil                    int `json:"NM_holofoil,omitempty"`
	NMReverseHolofoil             int `json:"NM_reverseholofoil,omitempty"`
	NMFirstEdition                int `json:"NM_1stedition,omitempty"`
	NMUnlimited                   int `json:"NM_unlimited,omitempty"`
	NMLimited                     int `json:"NM_limited,omitempty"`
	NMFirstEditionHolofoil        int `json:"NM_1steditionholofoil,omitempty"`
	NMUnlimitedHolofoil           int `json:"NM_unlimitedholofoil,omitempty"`
	NMFirstEditionNormal          int `json:"NM_1steditionnormal,omitempty"`
	NMFirstEditionRainbowFoil     int `json:"NM_1steditionrainbowfoil,omitempty"`
	NMFirstEditionColdFoil        int `json:"NM_1steditioncoldfoil,omitempty"`
	NMUnlimitedEditionNormal      int `json:"NM_unlimitededitionnormal,omitempty"`
	NMUnlimitedEditionRainbowFoil int `json:"NM_unlimitededitionrainbowfoil,omitempty"`
	SPRainbowFoil                 int `json:"SP_rainbowfoil,omitempty"`
	SPColdFoil                    int `json:"SP_coldfoil,omitempty"`
	SPHolofoil                    int `json:"SP_holofoil,omitempty"`
	SPReverseHolofoil             int `json:"SP_reverseholofoil,omitempty"`
	SPFirstEdition                int `json:"SP_1stedition,omitempty"`
	SPUnlimited                   int `json:"SP_unlimited,omitempty"`
	SPLimited                     int `json:"SP_limited,omitempty"`
	SPFirstEditionHolofoil        int `json:"SP_1steditionholofoil,omitempty"`
	SPUnlimitedHolofoil           int `json:"SP_unlimitedholofoil,omitempty"`
	SPFirstEditionNormal          int `json:"SP_1steditionnormal,omitempty"`
	SPFirstEditionRainbowFoil     int `json:"SP_1steditionrainbowfoil,omitempty"`
	SPFirstEditionColdFoil        int `json:"SP_1steditioncoldfoil,omitempty"`
	SPUnlimitedEditionNormal      int `json:"SP_unlimitededitionnormal,omitempty"`
	SPUnlimitedEditionRainbowFoil int `json:"SP_unlimitededitionrainbowfoil,omitempty"`
	MPRainbowFoil                 int `json:"MP_rainbowfoil,omitempty"`
	MPColdFoil                    int `json:"MP_coldfoil,omitempty"`
	MPHolofoil                    int `json:"MP_holofoil,omitempty"`
	MPReverseHolofoil             int `json:"MP_reverseholofoil,omitempty"`
	MPFirstEdition                int `json:"MP_1stedition,omitempty"`
	MPUnlimited                   int `json:"MP_unlimited,omitempty"`
	MPLimited                     int `json:"MP_limited,omitempty"`
	MPFirstEditionHolofoil        int `json:"MP_1steditionholofoil,omitempty"`
	MPUnlimitedHolofoil           int `json:"MP_unlimitedholofoil,omitempty"`
	MPFirstEditionNormal          int `json:"MP_1steditionnormal,omitempty"`
	MPFirstEditionRainbowFoil     int `json:"MP_1steditionrainbowfoil,omitempty"`
	MPFirstEditionColdFoil        int `json:"MP_1steditioncoldfoil,omitempty"`
	MPUnlimitedEditionNormal      int `json:"MP_unlimitededitionnormal,omitempty"`
	MPUnlimitedEditionRainbowFoil int `json:"MP_unlimitededitionrainbowfoil,omitempty"`
	HPRainbowFoil                 int `json:"HP_rainbowfoil,omitempty"`
	HPColdFoil                    int `json:"HP_coldfoil,omitempty"`
	HPHolofoil                    int `json:"HP_holofoil,omitempty"`
	HPReverseHolofoil             int `json:"HP_reverseholofoil,omitempty"`
	HPFirstEdition                int `json:"HP_1stedition,omitempty"`
	HPUnlimited                   int `json:"HP_unlimited,omitempty"`
	HPLimited                     int `json:"HP_limited,omitempty"`
	HPFirstEditionHolofoil        int `json:"HP_1steditionholofoil,omitempty"`
	HPUnlimitedHolofoil           int `json:"HP_unlimitedholofoil,omitempty"`
	HPFirstEditionNormal          int `json:"HP_1steditionnormal,omitempty"`
	HPFirstEditionRainbowFoil     int `json:"HP_1steditionrainbowfoil,omitempty"`
	HPFirstEditionColdFoil        int `json:"HP_1steditioncoldfoil,omitempty"`
	HPUnlimitedEditionNormal      int `json:"HP_unlimitededitionnormal,omitempty"`
	HPUnlimitedEditionRainbowFoil int `json:"HP_unlimitededitionrainbowfoil,omitempty"`
	PORainbowFoil                 int `json:"PO_rainbowfoil,omitempty"`
	POColdFoil                    int `json:"PO_coldfoil,omitempty"`
	POHolofoil                    int `json:"PO_holofoil,omitempty"`
	POReverseHolofoil             int `json:"PO_reverseholofoil,omitempty"`
	POFirstEdition                int `json:"PO_1stedition,omitempty"`
	POUnlimited                   int `json:"PO_unlimited,omitempty"`
	POLimited                     int `json:"PO_limited,omitempty"`
	POFirstEditionHolofoil        int `json:"PO_1steditionholofoil,omitempty"`
	POUnlimitedHolofoil           int `json:"PO_unlimitedholofoil,omitempty"`
	POFirstEditionNormal          int `json:"PO_1steditionnormal,omitempty"`
	POFirstEditionRainbowFoil     int `json:"PO_1steditionrainbowfoil,omitempty"`
	POFirstEditionColdFoil        int `json:"PO_1steditioncoldfoil,omitempty"`
	POUnlimitedEditionNormal      int `json:"PO_unlimitededitionnormal,omitempty"`
	POUnlimitedEditionRainbowFoil int `json:"PO_unlimitededitionrainbowfoil,omitempty"`
}

func (m *MoreQuantities) ref(tag string) *int {
	switch tag {
	case "NM_rainbowfoil":
		return &m.NMRainbowFoil
	case "NM_coldfoil":
		return &m.NMColdFoil
	case "NM_holofoil":
		return &m.NMHolofoil
	case "NM_reverseholofoil":
		return &m.NMReverseHolofoil
	case "NM_1stedition":
		return &m.NMFirstEdition
	case "NM_unlimited":
		return &m.NMUnlimited
	case "NM_limited":
		return &m.NMLimited
	case "NM_1steditionholofoil":
		return &m.NMFirstEditionHolofoil
	case "NM_unlimitedholofoil":
		return &m.NMUnlimitedHolofoil
	case "NM_1steditionnormal":
		return &m.NMFirstEditionNormal
	case "NM_1steditionrainbowfoil":
		return &m.NMFirstEditionRainbowFoil
	case "NM_1steditioncoldfoil":
		return &m.NMFirstEditionColdFoil
	case "NM_unlimitededitionnormal":
		return &m.NMUnlimitedEditionNormal
	case "NM_unlimitededitionrainbowfoil":
		return &m.NMUnlimitedEditionRainbowFoil
	case "SP_rainbowfoil":
		return &m.SPRainbowFoil
	case "SP_coldfoil":
		return &m.SPColdFoil
	case "SP_holofoil":
		return &m.SPHolofoil
	case "SP_reverseholofoil":
		return &m.SPReverseHolofoil
	case "SP_1stedition":
		return &m.SPFirstEdition
	case "SP_unlimited":
		return &m.SPUnlimited
	case "SP_limited":
		return &m.SPLimited
	case "SP_1steditionholofoil":
		return &m.SPFirstEditionHolofoil
	case "SP_unlimitedholofoil":
		return &m.SPUnlimitedHolofoil
	case "SP_1steditionnormal":
		return &m.SPFirstEditionNormal
	case "SP_1steditionrainbowfoil":
		return &m.SPFirstEditionRainbowFoil
	case "SP_1steditioncoldfoil":
		return &m.SPFirstEditionColdFoil
	case "SP_unlimitededitionnormal":
		return &m.SPUnlimitedEditionNormal
	case "SP_unlimitededitionrainbowfoil":
		return &m.SPUnlimitedEditionRainbowFoil
	case "MP_rainbowfoil":
		return &m.MPRainbowFoil
	case "MP_coldfoil":
		return &m.MPColdFoil
	case "MP_holofoil":
		return &m.MPHolofoil
	case "MP_reverseholofoil":
		return &m.MPReverseHolofoil
	case "MP_1stedition":
		return &m.MPFirstEdition
	case "MP_unlimited":
		return &m.MPUnlimited
	case "MP_limited":
		return &m.MPLimited
	case "MP_1steditionholofoil":
		return &m.MPFirstEditionHolofoil
	case "MP_unlimitedholofoil":
		return &m.MPUnlimitedHolofoil
	case "MP_1steditionnormal":
		return &m.MPFirstEditionNormal
	case "MP_1steditionrainbowfoil":
		return &m.MPFirstEditionRainbowFoil
	case "MP_1steditioncoldfoil":
		return &m.MPFirstEditionColdFoil
	case "MP_unlimitededitionnormal":
		return &m.MPUnlimitedEditionNormal
	case "MP_unlimitededitionrainbowfoil":
		return &m.MPUnlimitedEditionRainbowFoil
	case "HP_rainbowfoil":
		return &m.HPRainbowFoil
	case "HP_coldfoil":
		return &m.HPColdFoil
	case "HP_holofoil":
		return &m.HPHolofoil
	case "HP_reverseholofoil":
		return &m.HPReverseHolofoil
	case "HP_1stedition":
		return &m.HPFirstEdition
	case "HP_unlimited":
		return &m.HPUnlimited
	case "HP_limited":
		return &m.HPLimited
	case "HP_1steditionholofoil":
		return &m.HPFirstEditionHolofoil
	case "HP_unlimitedholofoil":
		return &m.HPUnlimitedHolofoil
	case "HP_1steditionnormal":
		return &m.HPFirstEditionNormal
	case "HP_1steditionrainbowfoil":
		return &m.HPFirstEditionRainbowFoil
	case "HP_1steditioncoldfoil":
		return &m.HPFirstEditionColdFoil
	case "HP_unlimitededitionnormal":
		return &m.HPUnlimitedEditionNormal
	case "HP_unlimitededitionrainbowfoil":
		return &m.HPUnlimitedEditionRainbowFoil
	case "PO_rainbowfoil":
		return &m.PORainbowFoil
	case "PO_coldfoil":
		return &m.POColdFoil
	case "PO_holofoil":
		return &m.POHolofoil
	case "PO_reverseholofoil":
		return &m.POReverseHolofoil
	case "PO_1stedition":
		return &m.POFirstEdition
	case "PO_unlimited":
		return &m.POUnlimited
	case "PO_limited":
		return &m.POLimited
	case "PO_1steditionholofoil":
		return &m.POFirstEditionHolofoil
	case "PO_unlimitedholofoil":
		return &m.POUnlimitedHolofoil
	case "PO_1steditionnormal":
		return &m.POFirstEditionNormal
	case "PO_1steditionrainbowfoil":
		return &m.POFirstEditionRainbowFoil
	case "PO_1steditioncoldfoil":
		return &m.POFirstEditionColdFoil
	case "PO_unlimitededitionnormal":
		return &m.POUnlimitedEditionNormal
	case "PO_unlimitededitionrainbowfoil":
		return &m.POUnlimitedEditionRainbowFoil
	}
	return nil
}
