//go:build ignore

// gen writes finishes_gen.go: the named fields, and the switches that
// reach them by name, for every finish past nonfoil, foil and etched.
// Edit extraFinishes below and run go generate ./banprice to add one.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"log"
	"os"
)

// extraFinishes are the finishes the datastore games sell past the three
// Magic has, spelled as mtgmatcher.FinishSlug spells them, each with the
// Go name its fields are given.
var extraFinishes = []struct{ slug, name string }{
	{"rainbowfoil", "RainbowFoil"},
	{"coldfoil", "ColdFoil"},
	{"holofoil", "Holofoil"},
	{"reverseholofoil", "ReverseHolofoil"},
	{"1stedition", "FirstEdition"},
	{"unlimited", "Unlimited"},
	{"limited", "Limited"},
	{"1steditionholofoil", "FirstEditionHolofoil"},
	{"unlimitedholofoil", "UnlimitedHolofoil"},
	{"1steditionnormal", "FirstEditionNormal"},
	{"1steditionrainbowfoil", "FirstEditionRainbowFoil"},
	{"1steditioncoldfoil", "FirstEditionColdFoil"},
	{"unlimitededitionnormal", "UnlimitedEditionNormal"},
	{"unlimitededitionrainbowfoil", "UnlimitedEditionRainbowFoil"},
}

var grades = []string{"NM", "SP", "MP", "HP", "PO"}

func main() {
	var b bytes.Buffer
	p := func(format string, args ...any) { fmt.Fprintf(&b, format+"\n", args...) }

	p("// Code generated by gen.go; DO NOT EDIT.")
	p("")
	p("package banprice")
	p("")

	p("// extraFinishes are the finishes MoreFinishes carries, in field order.")
	p("var extraFinishes = []string{")
	for _, f := range extraFinishes {
		p("\t%q,", f.slug)
	}
	p("}")
	p("")

	p("// MoreFinishes holds the prices and quantities of the finishes past")
	p("// nonfoil, foil and etched, which only the datastore games sell. Price")
	p("// embeds it by pointer, so its fields sit beside regular and foil on the")
	p("// wire and cost nothing for a card sold in none of them.")
	p("type MoreFinishes struct {")
	for _, f := range extraFinishes {
		p("\t%s float64 `json:\"%s,omitempty\"`", f.name, f.slug)
	}
	for _, f := range extraFinishes {
		p("\tQty%s int `json:\"qty_%s,omitempty\"`", f.name, f.slug)
	}
	p("}")
	p("")

	p("func (m *MoreFinishes) price(finish string) *float64 {")
	p("\tswitch finish {")
	for _, f := range extraFinishes {
		p("\tcase %q:", f.slug)
		p("\t\treturn &m.%s", f.name)
	}
	p("\t}")
	p("\treturn nil")
	p("}")
	p("")

	p("func (m *MoreFinishes) qty(finish string) *int {")
	p("\tswitch finish {")
	for _, f := range extraFinishes {
		p("\tcase %q:", f.slug)
		p("\t\treturn &m.Qty%s", f.name)
	}
	p("\t}")
	p("\treturn nil")
	p("}")
	p("")

	for _, kind := range []struct{ name, typ, doc string }{
		{"MoreConditions", "float64", "per-grade prices"},
		{"MoreQuantities", "int", "per-grade quantities"},
	} {
		p("// %s holds the %s of the finishes MoreFinishes", kind.name, kind.doc)
		p("// carries, embedded by pointer for the same reason.")
		p("type %s struct {", kind.name)
		for _, g := range grades {
			for _, f := range extraFinishes {
				p("\t%s%s %s `json:\"%s_%s,omitempty\"`", g, f.name, kind.typ, g, f.slug)
			}
		}
		p("}")
		p("")
		p("func (m *%s) ref(tag string) *%s {", kind.name, kind.typ)
		p("\tswitch tag {")
		for _, g := range grades {
			for _, f := range extraFinishes {
				p("\tcase \"%s_%s\":", g, f.slug)
				p("\t\treturn &m.%s%s", g, f.name)
			}
		}
		p("\t}")
		p("\treturn nil")
		p("}")
		p("")
	}

	out, err := format.Source(b.Bytes())
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("finishes_gen.go", out, 0o644); err != nil {
		log.Fatal(err)
	}
}
