name: beta-deploy

on:
  push:
    tags:
      - 'beta-*' # deploy only when a new tag is created
  workflow_dispatch:
    inputs:
      skip_ci:
        description: "Deploy without checking that CI passed"
        type: boolean
        default: false

permissions: {}

jobs:
  ci:
    uses: ./.github/workflows/ci-passed.yml
    with:
      ref: ${{ github.ref_name }}
      skip: ${{ inputs.skip_ci == true }}
    permissions:
      actions: read
      contents: read

  deploy:
    needs: ci
    runs-on: ubuntu-latest
    steps:
      - name: Install doctl
        uses: digitalocean/action-doctl@v2.5.2
        with:
          token: ${{ secrets.DO_API_TOKEN }}

      - name: Create deployment
        run: doctl apps create-deployment ${{ secrets.DO_BETA_APP_ID }} --wait

