name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: ${{ secrets.SERVICE_NAME }}
  IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/${{ secrets.SERVICE_NAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.CLOUDRUNNER }}
          export_default_credentials: true

      - name: Build and push Docker image
        run: |
          docker build -t ${{ env.IMAGE }} .
          docker push ${{ env.IMAGE }}

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} --image ${{ env.IMAGE }} --cpu=2 --max-instances=50 --set-secrets=/mnt/config.json=${{ secrets.CONFIG }},/mnt1/credentials.json=${{ secrets.FIREBASE_SA }},/mnt2/creds.json=${{ secrets.CLOUDRUNNER }},/mnt3/client-secret.json=${{ secrets.CLIENT_SECRET }} --execution-environment=gen2 --region us-central1 --project=${{ env.PROJECT_ID }} --platform managed --allow-unauthenticated
      - name: Update traffic to latest
        run: gcloud run services update-traffic ${{ env.SERVICE_NAME }} --to-latest --region us-central1 --project=${{ env.PROJECT_ID }}
